---
# Service account for backend components handling data processing, 
# quality validation, and pipeline orchestration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-backend-sa
  namespace: self-healing-pipeline
  labels:
    app: self-healing-pipeline
    component: backend
    environment: ${ENV}
    managed-by: kustomize
  annotations:
    description: "Service account for backend components of the self-healing data pipeline"
    iam.gke.io/gcp-service-account: pipeline-backend@${PROJECT_ID}.iam.gserviceaccount.com
---
# Service account for web frontend components providing user interface and dashboards
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-web-sa
  namespace: self-healing-pipeline
  labels:
    app: self-healing-pipeline
    component: web
    environment: ${ENV}
    managed-by: kustomize
  annotations:
    description: "Service account for web frontend components of the self-healing data pipeline"
    iam.gke.io/gcp-service-account: pipeline-web@${PROJECT_ID}.iam.gserviceaccount.com
---
# Service account for monitoring components with broader cluster visibility permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-monitoring-sa
  namespace: self-healing-pipeline
  labels:
    app: self-healing-pipeline
    component: monitoring
    environment: ${ENV}
    managed-by: kustomize
  annotations:
    description: "Service account for monitoring components of the self-healing data pipeline"
    iam.gke.io/gcp-service-account: pipeline-monitoring@${PROJECT_ID}.iam.gserviceaccount.com
---
# Service account for self-healing AI components that can modify resources to implement corrections
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-healing-sa
  namespace: self-healing-pipeline
  labels:
    app: self-healing-pipeline
    component: self-healing
    environment: ${ENV}
    managed-by: kustomize
  annotations:
    description: "Service account for self-healing AI components of the self-healing data pipeline"
    iam.gke.io/gcp-service-account: pipeline-healing@${PROJECT_ID}.iam.gserviceaccount.com