apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config-dev
  namespace: self-healing-pipeline-dev
  labels:
    app: data-pipeline
    component: common
    environment: development
    managed-by: kustomize
data:
  LOG_LEVEL: "DEBUG"
  ENABLE_METRICS: "true"
  METRICS_EXPORT_INTERVAL_SECONDS: "30"
  GCP_PROJECT_ID: "self-healing-pipeline-dev"
  GCP_REGION: "us-central1"
  GCP_ZONE: "us-central1-a"
  COMPOSER_ENVIRONMENT: "self-healing-pipeline-dev"
  BIGQUERY_DATASET: "self_healing_pipeline_dev"
  GCS_BUCKET: "self-healing-pipeline-dev"
  API_TIMEOUT_SECONDS: "60"
  MAX_RETRIES: "5"
  RETRY_BACKOFF_FACTOR: "1.5"
  ENABLE_TRACING: "true"
  ENABLE_PROFILING: "true"
  BATCH_SIZE: "500"
  MAX_BATCH_SIZE: "5000"
  PARALLEL_WORKERS: "3"
  MAX_PARALLEL_WORKERS: "10"
  ENABLE_VERBOSE_LOGGING: "true"
  ENABLE_LOCAL_DEVELOPMENT: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quality-config-dev
  namespace: self-healing-pipeline-dev
  labels:
    app: data-pipeline
    component: quality
    environment: development
    managed-by: kustomize
data:
  VALIDATION_TIMEOUT_SECONDS: "600"
  QUALITY_SCORE_THRESHOLD: "75"
  SCHEMA_VALIDATION_ENABLED: "true"
  CONTENT_VALIDATION_ENABLED: "true"
  RELATIONSHIP_VALIDATION_ENABLED: "true"
  STATISTICAL_VALIDATION_ENABLED: "true"
  VALIDATION_BATCH_SIZE: "500"
  EXPECTATIONS_STORAGE_PATH: "/app/expectations"
  VALIDATION_RESULTS_DATASET: "self_healing_pipeline_dev"
  VALIDATION_RESULTS_TABLE: "quality_validation_results"
  GREAT_EXPECTATIONS_VERSION: "0.15.50"
  CRITICAL_THRESHOLD: "0.5"
  WARNING_THRESHOLD: "0.7"
  AUTO_FIX_ENABLED: "true"
  NOTIFICATION_ON_FAILURE: "true"
  ENABLE_VALIDATION_DEBUGGING: "true"
  SAVE_VALIDATION_SAMPLES: "true"
  MAX_VALIDATION_SAMPLES: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: healing-config-dev
  namespace: self-healing-pipeline-dev
  labels:
    app: data-pipeline
    component: self-healing
    environment: development
    managed-by: kustomize
data:
  HEALING_MODE: "SEMI_AUTOMATIC"
  CONFIDENCE_THRESHOLD: "70"
  MAX_RETRY_ATTEMPTS: "5"
  APPROVAL_REQUIRED_CRITICAL: "false"
  APPROVAL_REQUIRED_HIGH: "false"
  APPROVAL_REQUIRED_MEDIUM: "false"
  APPROVAL_REQUIRED_LOW: "false"
  LEARNING_MODE: "active"
  MODEL_REGISTRY: "models/dev"
  MODEL_VERSION: "latest"
  VERTEX_AI_ENDPOINT: "projects/self-healing-pipeline-dev/locations/us-central1/endpoints/self-healing-endpoint"
  ISSUE_PATTERN_DATASET: "self_healing_pipeline_dev"
  ISSUE_PATTERN_TABLE: "issue_patterns"
  HEALING_ACTIONS_DATASET: "self_healing_pipeline_dev"
  HEALING_ACTIONS_TABLE: "healing_actions"
  HEALING_EXECUTIONS_DATASET: "self_healing_pipeline_dev"
  HEALING_EXECUTIONS_TABLE: "healing_executions"
  DATA_CORRECTION_CONFIDENCE_THRESHOLD: "70"
  PIPELINE_ADJUSTMENT_CONFIDENCE_THRESHOLD: "65"
  RESOURCE_OPTIMIZATION_CONFIDENCE_THRESHOLD: "60"
  RECOVERY_CONFIDENCE_THRESHOLD: "75"
  VERSION_RETENTION: "10"
  RETRAINING_INTERVAL_DAYS: "1"
  ENABLE_MOCK_MODELS: "true"
  ENABLE_HEALING_DEBUGGING: "true"
  SAVE_HEALING_ATTEMPTS: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config-dev
  namespace: self-healing-pipeline-dev
  labels:
    app: data-pipeline
    component: monitoring
    environment: development
    managed-by: kustomize
data:
  ALERT_SEVERITY_LEVELS: "critical,high,medium,low"
  CRITICAL_ALERT_THRESHOLD: "1"
  HIGH_ALERT_THRESHOLD: "3"
  MEDIUM_ALERT_THRESHOLD: "5"
  LOW_ALERT_THRESHOLD: "10"
  TEAMS_WEBHOOK_ENABLED: "true"
  TEAMS_WEBHOOK_URL: "https://dev-webhook.example.com/teams"
  EMAIL_ALERTS_ENABLED: "true"
  EMAIL_RECIPIENTS: "dev-alerts@example.com,dev-team@example.com"
  ALERT_CORRELATION_ENABLED: "true"
  ANOMALY_DETECTION_ENABLED: "true"
  METRICS_RETENTION_DAYS: "15"
  DASHBOARD_REFRESH_INTERVAL_SECONDS: "60"
  ALERT_ESCALATION_MINUTES: "30"
  MONITORING_DATASET: "self_healing_pipeline_dev"
  ALERTS_TABLE: "pipeline_alerts"
  METRICS_TABLE: "pipeline_metrics"
  METRICS_COLLECTION_INTERVAL_SECONDS: "30"
  LOG_ANALYSIS_ENABLED: "true"
  ANOMALY_DETECTION_SENSITIVITY: "0.6"
  ANOMALY_DETECTION_TRAINING_PERIOD_DAYS: "5"
  ANOMALY_DETECTION_MIN_DATA_POINTS: "50"
  ALERT_DEDUPLICATION_WINDOW_MINUTES: "5"
  PIPELINE_FAILURE_RATE_WARNING: "0.1"
  PIPELINE_FAILURE_RATE_CRITICAL: "0.2"
  DATA_PROCESSING_LATENCY_WARNING: "0.3"
  DATA_PROCESSING_LATENCY_CRITICAL: "0.6"
  QUALITY_VALIDATION_FAILURE_WARNING: "0.05"
  QUALITY_VALIDATION_FAILURE_CRITICAL: "0.1"
  SELF_HEALING_SUCCESS_RATE_WARNING: "0.8"
  SELF_HEALING_SUCCESS_RATE_CRITICAL: "0.6"
  RESOURCE_UTILIZATION_WARNING: "0.6"
  RESOURCE_UTILIZATION_CRITICAL: "0.8"
  ERROR_RATE_WARNING: "5.0"
  ERROR_RATE_CRITICAL: "10.0"
  ENABLE_DEBUG_ALERTS: "true"
  ENABLE_ALERT_TESTING: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-feature-flags
  namespace: self-healing-pipeline-dev
  labels:
    app: data-pipeline
    component: feature-flags
    environment: development
    managed-by: kustomize
data:
  ENABLE_AI_PREDICTIONS: "true"
  ENABLE_ADVANCED_MONITORING: "true"
  ENABLE_EXPERIMENTAL_FEATURES: "true"
  ENABLE_SELF_HEALING: "true"
  ENABLE_QUERY_OPTIMIZATION: "true"
  ENABLE_SCHEMA_OPTIMIZATION: "true"
  ENABLE_RESOURCE_OPTIMIZATION: "true"
  ENABLE_AUTO_IMPLEMENTATION: "true"
  ENABLE_APPROVAL_WORKFLOW: "false"
  ENABLE_MOCK_DATA: "true"
  ENABLE_DEBUG_TOOLS: "true"
  ENABLE_PERFORMANCE_TESTING: "true"
  ENABLE_AI_PLAYGROUND: "true"
  ENABLE_FEATURE_TESTING: "true"
  ENABLE_CHAOS_TESTING: "true"