{{- if or .Values.backend.enabled .Values.web.enabled }}

{{- if .Values.config.secrets.databaseCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-db-credentials
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: secrets
  annotations:
    description: "Database credentials for the self-healing data pipeline"
type: Opaque
data:
  CLOUDSQL_USER: {{ .Values.config.secrets.databaseCredentials.cloudsqlUser | b64enc }}
  CLOUDSQL_PASSWORD: {{ .Values.config.secrets.databaseCredentials.cloudsqlPassword | b64enc }}
  CLOUDSQL_CONNECTION_NAME: {{ .Values.config.secrets.databaseCredentials.cloudsqlConnectionName | b64enc }}
{{- end }}

{{- if .Values.config.secrets.apiKeys.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-api-keys
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: secrets
  annotations:
    description: "API keys for external service integration"
type: Opaque
data:
  EXTERNAL_API_KEY: {{ .Values.config.secrets.apiKeys.externalApiKey | b64enc }}
{{- end }}

{{- if .Values.config.secrets.oauthCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-oauth-credentials
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: secrets
  annotations:
    description: "OAuth credentials for authentication"
type: Opaque
data:
  CLIENT_ID: {{ .Values.config.secrets.oauthCredentials.clientId | b64enc }}
  CLIENT_SECRET: {{ .Values.config.secrets.oauthCredentials.clientSecret | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-notification-credentials
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: secrets
  annotations:
    description: "Credentials for notification services"
type: Opaque
data:
  TEAMS_WEBHOOK_DATA_ENGINEERING: {{ .Values.config.secrets.notificationCredentials.teamsWebhookDataEngineering | default "" | b64enc }}
  TEAMS_WEBHOOK_OPERATIONS: {{ .Values.config.secrets.notificationCredentials.teamsWebhookOperations | default "" | b64enc }}
  TEAMS_WEBHOOK_DATA_QUALITY: {{ .Values.config.secrets.notificationCredentials.teamsWebhookDataQuality | default "" | b64enc }}
  EMAIL_SENDER: {{ .Values.config.secrets.notificationCredentials.emailSender | default "pipeline-alerts@example.com" | b64enc }}
  SMTP_SERVER: {{ .Values.config.secrets.notificationCredentials.smtpServer | default "" | b64enc }}
  SMTP_PORT: {{ .Values.config.secrets.notificationCredentials.smtpPort | default "587" | b64enc }}
  SMTP_USERNAME: {{ .Values.config.secrets.notificationCredentials.smtpUsername | default "" | b64enc }}
  SMTP_PASSWORD: {{ .Values.config.secrets.notificationCredentials.smtpPassword | default "" | b64enc }}

{{- if .Values.security.serviceAccount.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-gcp-sa
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: secrets
  annotations:
    description: "GCP service account key for the self-healing data pipeline"
type: Opaque
data:
  key.json: {{ .Values.security.serviceAccount.key | default "" | b64enc }}
{{- end }}

{{- end }}