{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-backend
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: backend
  annotations:
    description: "Service for backend API of the self-healing data pipeline"
    {{- with .Values.backend.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.backend.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "self-healing-pipeline.selectorLabels" . | nindent 4 }}
    component: backend
  sessionAffinity: None
{{- end }}

{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-healing-pipeline.fullname" . }}-web
  labels:
    {{- include "self-healing-pipeline.labels" . | nindent 4 }}
    component: web
  annotations:
    description: "Service for web UI of the self-healing data pipeline"
    {{- with .Values.web.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "self-healing-pipeline.selectorLabels" . | nindent 4 }}
    component: web
  sessionAffinity: None
{{- end }}