apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            cpu: 750m
            memory: 1.5Gi
          limits:
            cpu: 1500m
            memory: 3Gi
        env:
        - name: ENVIRONMENT
          value: staging
        - name: LOG_LEVEL
          value: info
        - name: ENABLE_PROFILING
          value: "false"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: ENABLE_SELF_HEALING
          value: "true"
        - name: MONITORING_INTERVAL
          value: "60"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: config-volume
          mountPath: /etc/config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: google-cloud-key
        secret:
          secretName: staging-credentials
      - name: config-volume
        configMap:
          name: pipeline-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - self-healing-pipeline
              topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 1Gi
        env:
        - name: ENVIRONMENT
          value: staging
        - name: API_URL
          value: https://api-staging.self-healing-pipeline.example.com
        - name: ENABLE_MOCK_DATA
          value: "false"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - self-healing-pipeline
              topologyKey: kubernetes.io/hostname