apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: self-healing-pipeline
  labels:
    app: self-healing-pipeline
    component: backend
    environment: ${ENV}
    managed-by: kustomize
  annotations:
    description: "Service for backend API of the self-healing data pipeline"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: self-healing-pipeline
    component: backend
  sessionAffinity: None